CREATE TABLE TBL_USER (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	NATIONALITY VARCHAR(255) NOT NULL,
	OCCUPATION VARCHAR(255) NOT NULL,
	KNOWN_FOR VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PHONE VARCHAR(255) NOT NULL
);